name: Build and Test

on:
  push:
    branches-ignore:
      - trash
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Pester
        shell: pwsh
        run: Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Build and Display README
        shell: pwsh
        run: |
          ./Build-Readme.ps1
          $readme = Get-Content README.md -Raw
          "::group::Generated README"
          $readme
          "::endgroup::"

      - name: Run Tests
        shell: pwsh
        run: Invoke-Pester "./tests" -Output Detailed

      - name: Package and Upload
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path package -Force
          Copy-Item -Path "./SystemPathGroups","README.md" -Destination package -Recurse
          Compress-Archive -Path "package/*" -DestinationPath "SystemPathGroups.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: SystemPathGroups
          path: SystemPathGroups.zip