name: Build and Test

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  security-events: write

on:
  push:
    branches-ignore:
      - trash
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Pester
        shell: pwsh
        run: Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Build and Display README
        shell: pwsh
        run: |
          ./Build-Readme.ps1
          $readme = Get-Content README.md -Raw
          echo $readme >> $env:GITHUB_STEP_SUMMARY
      - name: Run Tests
        shell: pwsh
        run: |
          
          # Run the tests using our pester.tests.ps1
          & "$PWD\tests\pester.tests.ps1"


      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: PowerShell Tests
          path: test-results.xml
          reporter: jest-junit
          fail-on-error: true

      - name: Package and Upload
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path package -Force
          Copy-Item -Path "./SystemPathGroups","README.md" -Destination package -Recurse
          Compress-Archive -Path "package/*" -DestinationPath "SystemPathGroups.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: SystemPathGroups
          path: SystemPathGroups.zip